### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by bcheggeseth** [Ericwentz5/NBA_Comparison_Project#1]
**Requested File Structure**
- [x] code
- [x] data
- [x] planning with Milestone1.qmd  

**.gitignore**
- [x] Created a .gitignore file
- [x] Contains all of the request files in it

**Milestone2.qmd**
- [x] Progress on the stated plan
- [x] Future plan for Milestone 3
- I encourage you to copy all the data cleaning code to a cleaning.R file in code and now put Milestone2.qmd and html into planning. Have a separate analysis qmd files to explore the data and add all "cleaning" code to cleaning.R so that you can source('cleaning.R') in any analysis qmd. 
- [x] Included sessionInfo() at the end of qmd files

General Feedback:

- There are opportunities to use across() to convert many variables to numeric. But it looks like it was already numeric based on the str()
- Here is a resource about Gower's distance: https://en.wikipedia.org/wiki/Gower%27s_distance
- Why filter based on 528 minutes? Is that threshold significant in the context?
- You don't need a model to scale values to 0-1 (min - max).
- While you are planning an application, you also need to consider what story you plan to tell and that will involve choices on your part. 

Collaboration:

- I will check git commits to ensure everyone contributes.
- Neel did not make any commits this time; I know you were all sitting together but make sure going forward each of you are making individual contributions on your own computers.
