### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by lsokolew** [Ericwentz5/NBA_Comparison_Project#2]
Milestone 3 Feedback

**Requested File Structure**
- [x] results folder 
- [x] with Milestone3-Blog.qmd 
- [x] with rendered html
- [ ] Included sessionInfo() at the end of qmd files
- only in milestone 1 & 2 qmds currently

**Progress from Milestone 2**
- [ ] Progress on the stated plan
- could not tell from the blog post

**Milestone3-Blog**
images aren’t appearing in your HTML; try adding embed-resources: true to your qmd
Not much info provided 
- [x] < 1000 words
- [ ] Motivate the importance of the topic
- [ ] Lead the reader through the rationale for the narrowing/focusing of the scope via the main 2-3 broad questions
- [ ] Tie results (plots and modeling output) to the broad questions and explain how all results fit together
- [ ] End with main takeaways, limitations with regard to the data context and ethical considerations, and future directions
